# config/packages/vich_uploader.yaml
vich_uploader:
    db_driver: orm

    mappings:
        profil_photo:
            uri_prefix: /uploads/profils
            upload_destination: '%kernel.project_dir%/public/uploads/profils'